services:
  react_front:
    build: docker/react-front/.
    container_name: "react_front"
    volumes:
      - ./react-front:/usr/app/react-front/.
    ports:
      - "3000:3000"
  express_back:
    build: docker/express-back/.
    container_name: "express_back"
    volumes:
      - ./express-back:/usr/app/express-back/.
    ports:
      - "9999:9999"
  json_server:
    build: docker/json-server/.
    container_name: "json_server"
    volumes:
      - ./json-server:/usr/app/json-server/.
    ports:
     - "8081:8080"
  db:
    image: postgres
    container_name: "db"
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=odeone
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - "8080:8080"
