services:
  react_front:
    build: docker/react-front/.
    container_name: "react_front"
    volumes:
      - ./react-front:/usr/app/react-front/.
    ports:
      - "3000:3000"
  json_server:
    build: docker/json-server/.
    container_name: "json_server"
    volumes:
      - ./json-server:/usr/app/json-server/.
    ports:
     - "8080:8080"
